package com.android.carrierconfig;

/* This class is generated by JADX */
public final class R {

    public static final class xml {
        public static final int base = 2130837504;
        public static final int vendor = 2130837505;
    }
}
